name: Backend CI

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]
  pull_request:
    paths: ["backend/**"]

defaults:
  run:
    working-directory: backend

permissions:
  contents: read

jobs:
  compile:
    name: Compile Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/backend-setup
      - name: Syntax check
        run: python -m compileall src

  mypy:
    name: Type check (mypy)
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/backend-setup
      - name: Type check
        run: mypy src

  flake8:
    name: Lint (flake8)
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/backend-setup
      - name: Lint (flake8)
        run: flake8 src

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/backend-setup
      - name: Run unit tests
        run: |
          PYTHONPATH=src pytest tests/unit --maxfail=1 --disable-warnings -q


  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
      - name: Setup environment
        uses: ./.github/actions/backend-setup
      - name: Run integration tests
        run: |
          PYTHONPATH=src pytest tests/integration --maxfail=1 --disable-warnings -q

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [mypy, flake8, unit-tests, integration-tests]
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: |
          echo "ALLOWED_EMAIL=${{ secrets.ALLOWED_EMAIL }}" > src/.env
      - name: Create firebase key file
        run: |
          mkdir -p secrets
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > secrets/firebase-key.json
      - name: Build Docker image
        run: docker build -t wyrmhort-backend .
