name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

  compile:
    name: Compile Backend
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Syntax check
        run: python -m compileall src

  mypy:
    name: Type check (mypy)
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Type check
        run: mypy src

  flake8:
    name: Lint (flake8)
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Lint (flake8)
        run: flake8 src

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Run unit tests
        run: |
          PYTHONPATH=src pytest tests --maxfail=1 --disable-warnings -q

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [mypy, flake8, unit-tests]
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Create firebase key file
        run: |
          mkdir -p secrets
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" > secrets/firebase-key.json
      - name: Build Docker image
        run: docker build -t wyrmhort-backend .
