name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/frontend-setup
      - name: ESLint
        run: npm run lint

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/frontend-setup
      - name: Run tests
        run: npm test

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/frontend-setup
      - name: Build production bundle
        run: npm run build
