name: Frontend Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/frontend-setup
      - name: Create .env.production
        run: |
          cat > .env.production <<EOF
          VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENTS_ID=${{ secrets.VITE_FIREBASE_MEASUREMENTS_ID }}
          VITE_ALLOWED_EMAIL=${{ secrets.ALLOWED_EMAIL }}
          EOF
      - name: Debug env file
        run: cat .env.production
      - name: Build frontend
        run: |
          npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GCP_SA_KEY }}'
          channelId: live
          projectId: wyrmhort
      - name: Health check
        run: |
          curl --fail https://wyrmhort.web.app/ || (echo "Frontend failed to deploy!" && exit 1)
