name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: ESLint
        run: npm run lint

  test:
    name: Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm test -- --coverage --watchAll=false

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Build production bundle
        run: npm run build
