name: Snyk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk-scans:
    name: Run Snyk Scans
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Backend SAST
          - id: backend-sast
            component: backend
            scan_name: "Static Application Security Testing (SAST)"
            working_dir: backend
            setup_action: ./.github/actions/backend-setup
            snyk_cmd: snyk code test --sarif-file-output=snyk-backend-sast.sarif
            sarif_file: snyk-backend-sast.sarif

          # Backend SCA
          - id: backend-sca
            component: backend
            scan_name: "Software Composition Analysis (SCA)"
            working_dir: backend
            setup_action: ./.github/actions/backend-setup
            snyk_cmd: snyk test --file=requirements.txt --sarif-file-output=snyk-backend-sca.sarif
            sarif_file: snyk-backend-sca.sarif

          # Backend Docker
          - id: backend-docker
            component: backend
            scan_name: "Container Image Scan"
            working_dir: backend
            setup_action: ./.github/actions/backend-setup
            snyk_cmd: snyk container test wyrmhort-backend --severity-threshold=medium --sarif-file-output=snyk-docker.sarif
            sarif_file: snyk-docker.sarif

          # Frontend SAST
          - id: frontend-sast
            component: frontend
            scan_name: "Static Application Security Testing (SAST)"
            working_dir: frontend
            setup_action: ./.github/actions/frontend-setup
            snyk_cmd: snyk code test --sarif-file-output=snyk-frontend-sast.sarif
            sarif_file: snyk-frontend-sast.sarif

          # Frontend SCA
          - id: frontend-sca
            component: frontend
            scan_name: "Software Composition Analysis (SCA)"
            working_dir: frontend
            setup_action: ./.github/actions/frontend-setup
            snyk_cmd: snyk test --file=package.json --sarif-file-output=snyk-frontend-sca.sarif
            sarif_file: snyk-frontend-sca.sarif

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ${{ matrix.setup_action }}

      - name: Build Docker image
        if: ${{ matrix.id == 'backend-docker' }}
        run: docker build -t wyrmhort-backend -f Dockerfile .
        working-directory: backend

      - name: Cache npm for Snyk
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: snyk-cli-${{ runner.os }}

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: ${{ matrix.scan_name }}
        run: |
          ${{ matrix.snyk_cmd }} || echo "Snyk scan failed or limit reached"
        working-directory: ${{ matrix.working_dir }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Check SARIF file exists
        id: check_sarif
        run: |
          if [ -f "${{ matrix.sarif_file }}" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload SARIF results
        if: steps.check_sarif.outputs.exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ matrix.sarif_file }}
